# encoding: utf-8

class Chalk::GzMath::FalliblePointTag < GzMath::QuestionTag
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  # security (i.e. attr_accessible) ...........................................

  # relationships .............................................................

  has_many :fallible_point_tag_exercises, class_name: "GzMath::FalliblePointTagExercise"
  has_many :exam_exercises, class_name: "GzMath::ExamExercise", through: :fallible_point_tag_exercises

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
