# encoding: utf-8

class Chalk::GzMath::KeyStepTag < GzMath::QuestionTag
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection

  # security (i.e. attr_accessible) ...........................................

  attr_accessible :content, :name

  # relationships .............................................................

  has_many :key_step_tag_exercises, class_name: "GzMath::KeyStepTagExercise"
  has_many :exam_exercises, class_name: "GzMath::ExamExercise", through: :key_step_tag_exercises

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
