# encoding: utf-8

class Chalk::GzMath::OptionAnalysis < Chalk::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection

  # security (i.e. attr_accessible) ...........................................

  attr_accessible :analysis_a, :analysis_b, :analysis_c, :analysis_d, :exam_exercise_id

  # relationships .............................................................

  belongs_to :exam_exercise, class_name: "GzMath::ExamExercise"

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
