# encoding: utf-8

class Chalk::GzMath::SolvingIdeaTagExercise < Chalk::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  # security (i.e. attr_accessible) ...........................................

  attr_accessible :exam_exercise_id, :solving_idea_tag_id

  # relationships .............................................................

  belongs_to :exam_exercise, class_name: "GzMath::ExamExercise"
  belongs_to :solving_idea_tag, class_name: "GzMath::SolvingIdeaTag"

  # constants definition ......................................................

  # validations ...............................................................

  validates :exam_exercise_id, :solving_idea_tag_id, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
