# encoding: utf-8

class Chalk::GzMath::Tree < Chalk::Base
  # extends ...................................................................

  # includes ..................................................................
  include ActiveModel::ForbiddenAttributesProtection
  include TarActivity
  include TreeBase

  include OrderIdx
  order_idx_scope [:p_id]

  # relationships .............................................................
  has_many :keypoints, class_name: 'GzMath::Keypoint', dependent: :restrict,
    order: "order_idx ASC", conditions: "p_id IS NULL"

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................

  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def leaf?
    self.children.size == 0
  end

  # @note 挂靠点
  def leaf_keypoints 
    self.keypoints.map { |kp| kp.leaf_keypoints }.flatten
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
