# encoding: utf-8

class Chalk::KyEn::ExamPaperStructure < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  #include TarActivity
  # security (i.e. attr_accessible) ...........................................

  # relationships .............................................................
  belongs_to :exam_paper, class_name: "Chalk::KyEn::ExamPaper"
  belongs_to :exam_paper_structure, class_name: "Chalk::KyEn::ExamPaperStructure"

  has_many :exam_paper_structures, class_name: "Chalk::KyEn::ExamPaperStructure"
  has_many :exam_paper_exercises, class_name: "Chalk::KyEn::ExamPaperExercise"
  has_many :exam_paper_questions, class_name: "Chalk::KyEn::ExamPaperQuestion"

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................

  # additional config .........................................................
  establish_connection :chalk_production

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
