# encoding: utf-8

class ExamCategory < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  #include TarActivity

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :exam_type, :subject

  # relationships .............................................................

  # constants definition ......................................................
  EXAM_TYPE = Chalk::Enum.new %w(中考 高考 CET4 CET6 考研)

  SUBJECT = Chalk::Enum.new %w(语文 数学 英语 理综 物理 化学 生物 文综 政治 历史 地理)

  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def cet?
    exam_type == EXAM_TYPE['CET4'] || exam_type == EXAM_TYPE['CET6']
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
