class ExamPaperExtension < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  #include TarActivity

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :question_container_id, :source_paper_id, :import_status,
    :process_status, :name, :description, :year, :month, :source, :region_type,
    :province_id, :city_id, :district_id, :paper_no, :duration

  # relationships .............................................................
  belongs_to :question_container

  # constants definition ......................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
