# encoding: utf-8

class StudyResorce < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  #include ActiveModel::ForbiddenAttributesProtection
  #include TarActivity

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :exam_category_id, :knowledge_id, :behavior_type,
    :container_type, :container_id, :title, :description

  # relationships .............................................................

  # constants definition ......................................................
  BEHAVIOR_TYPE = Chalk::Enum.new({
    '练习' => 'Practice',
    '测试' => 'Examination'
  })

  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................

  # public instance methods ...................................................
  def container
    return nil if container_type.blank? || container_id.blank?
    container_type.constantize.where(id: container_id).first
  end

  def question_container
    container_type == "QuestionContainer" ? container : nil
  end

  def knowledge_container
    container_type == "KnowledgeContainer" ? container : nil
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
